In [3]:
#创建数组
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1,1]=10
print(a.shape)
print (b.shape)
print (a.dtype)
print (b)
print(a)

(3,)
(3, 3)
int64
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
[1 2 3]


In [20]:
#结构数组

import numpy as np
persontype = np.dtype({
    'names':['name', 'age', 'chinese', 'math', 'english'],
    'formats':['S32','i', 'i', 'i', 'f']})
peoples = np.array([("ZhangFei",32,75,100, 90),("GuanYu",24,85,96,88.5),
       ("ZhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)], dtype=persontype)
ages = peoples['age']
chineses = peoples['chinese']
maths = peoples['math']
englishs = peoples['english']
print(ages)
print(peoples)
print (np.mean(ages))
print (np.mean(chineses))
print (np.mean(maths))
print(np.mean(englishs))

[32 24 28 29]
[(b'ZhangFei', 32, 75, 100,  90. ) (b'GuanYu', 24, 85,  96,  88.5)
 (b'ZhaoYun', 28, 85,  92,  96.5) (b'HuangZhong', 29, 65,  85, 100. )]
28.25
77.5
93.25
93.75


In [21]:
#连续数组的创建
#range()，通过指定初始值、终值、步长

x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print(x1,x2)

[1 3 5 7 9] [1. 3. 5. 7. 9.]


In [22]:
#算数运算

x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print(np.add(x1, x2))
print (np.subtract(x1, x2))
print (np.multiply(x1, x2))
print (np.divide(x1, x2))
print (np.power(x1, x2))
#在取余函数里，你既可以用 np.remainder(x1, x2)，也可以用 np.mod(x1, x2)，结果是一样的。
print (np.remainder(x1, x2))

[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


In [24]:
#统计函数
#计数组 / 矩阵中的最大值函数 amax()，最小值函数 amin()

import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
#amin() 用于计算数组中的元素沿指定轴的最小值
print(np.amin(a))
print (np.amin(a,0))
print( np.amin(a,1))
print (np.amax(a))
print( np.amax(a,0))
print (np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [26]:
#统计最大值与最小值之差 ptp()

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (np.ptp(a))
print (np.ptp(a,0))
print (np.ptp(a,1))

8
[6 6 6]
[2 2 2]


In [28]:
#统计数组的百分位数 percentile()

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (np.percentile(a, 50))
print( np.percentile(a, 50, axis=0))
print (np.percentile(a, 50, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [29]:
#统计数组中的中位数 median()、平均数 mean()

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
#求中位数
print (np.median(a))
print( np.median(a, axis=0))
print (np.median(a, axis=1))
#求平均数
print (np.mean(a))
print (np.mean(a, axis=0))
print (np.mean(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [30]:
#统计数组中的加权平均值 average()

a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print (np.average(a))
print (np.average(a,weights=wts))

2.5
3.0


In [31]:
#统计数组中的标准差 std()、方差 var()

a = np.array([1,2,3,4])
print (np.std(a))
print( np.var(a))

1.118033988749895
1.25


In [35]:
#排序
#sort(a, axis=-1, kind=‘quicksort’, order=None)
#axis 默认是 -1，即沿着数组的最后一个轴进行排序

a = np.array([[4,3,2],[2,4,1]])
print(a.shape)
print (np.sort(a))
print (np.sort(a, axis=None))
print(np.sort(a, axis=0)  )
print (np.sort(a, axis=1)  )
#if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension
print (np.sort(a, axis=-1)  )

(2, 3)
[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]
[[2 3 4]
 [1 2 4]]


In [37]:
peoples = np.array(
        [
            ("zhangfei", 66, 65, 30),
            ("guanyu", 95, 85, 98),
            ("zhaoyun", 93, 92, 96),
            ("huangzhong", 90, 88, 77),
            ("dianwei", 80, 90, 90)
        ])
print(peoples.shape)

(5, 4)
